use_default_settings:
  engines:
    keep_only:
      - google
      - bing
      - duckduckgo
      - brave
      - wikipedia
      - google news

general:
  instance_name: "ThreeArch Search"
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "override-via-SEARXNG_SECRET-env-var"
  limiter: false

ui:
  static_use_hash: true
